- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3, virtualenv
      block:
        - apt:
            pkg:
              - python3
              - virtualenv
            update_cache: yes
      become: yes
    - name: Instalando dependências com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework
    - name: Removendo dependencias
      shell: 'rm -rf db.sqlite3 manage.py setup/'      
    - name: Iniciando o projeto
      shell: '. /home/ubuntu/venv/bin/activate;django-admin startproject setup /home/ubuntu/'
    - name: Alterando o host do settings
      lineinfile:
        path: /home/ubuntu/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
    - name: Executar venv e django
      shell: '. venv/bin/activate;python manage.py runserver 0.0.0.0:8000'